protected/controllers/AjaxController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\Contractor;
use app\models\Customer;
use app\models\History;
use app\models\Product;
use app\models\StatisticsForm;
use app\models\User;
use Yii;
use yii\bootstrap\Html;
use yii\helpers\ArrayHelper;

class AjaxController extends BaseController {

	public $layout = false;

	public function actionAddToCart($productId) {
		Product::addToCart($productId);
	}

	public function actionRemoveFromCart() {
		$productIds = Yii::$app->request->get('productId');
		if ($productIds) {
			Product::removeFromCart($productIds);
		}
	}

	public function actionGetCart() {
		$cart = Product::getCart();

		$productsInCartOrdered = [];
		if (count($cart)) {
			$productIds = array_keys($cart);
			$productsInCart = Product::find()->where(['id' => $productIds])->indexBy('id')->all();
			foreach ($productIds as $productId) {
				$productsInCartOrdered[$productId] = $productsInCart[$productId];
			}
			unset($productsInCart); // save memory)))
		}

		return $this->render('@parts/cart', [
			'products' => $productsInCartOrdered,
			'cart'     => $cart,
			'sum'      => Product::getCartSum(),
		]);
	}

	public function actionChangeQuantity($productId, $quantity) {
		$cart             = Product::getCart();
		$cart[$productId] = $quantity;
		Product::setCart($cart);
	}

	public function actionSaveHistory() {
		$history         = new History();
		$history->cart   = serialize(Product::getCart());
		if ($history->save()) {
			// -- Demo saving to the PDF (maybe not demo =)))
			/*$cart     = Product::getCart();
			$products = Product::findAll(array_keys($cart));

			$pdf = new \mPDF();
			$pdf->WriteHTML(
				$this->render('@views/mail/mail', [
					'comment'  => '',
					'cart'     => $cart,
					'products' => $products,
				])
			);
			$pdfPath = implode(DIRECTORY_SEPARATOR, [
				Yii::getAlias('@webroot'),
				'pdf',
			]);
			if (!file_exists($pdfPath)) {
				@mkdir($pdfPath);
			}
			$pdfName = "cart_{$history->id}.pdf";
			@file_put_contents(implode(DIRECTORY_SEPARATOR, [
				$pdfPath,
				$pdfName,
			]), $pdf->Output('', 'S'));*/
			// -- -- -- --

			Product::clearCart();
			return $this->redirect(['main/history']);
		}
		return $this->redirect(['main/catalog']);
	}

	public function actionGetCounter() {
		return $this->render('@parts/cart-counter');
	}

	public function actionGetJson() {
		$params = Yii::$app->request->get('params');
		return $this->renderJson(json_decode($params, true));
	}

	public function actionDeleteProduct($id) {
		return (int) Product::findOne($id)->delete();
	}

	public function actionDeleteUser($id) {
		if (User::find()->count() < 2) {
			return 0;
		}
		return (int) User::findOne($id)->delete();
	}

	public function actionChangeUser() {
		$attributes = Yii::$app->request->post(null, []);
		if (count($attributes) == 0) {
			Yii::$app->end();
		}

		/** @var User $user */
		$user = User::findOne($attributes['id']);
		$user->save(true, array_keys($attributes));

		// -- We can not switch off rules for password only, so copy password if exists
		if (isset($attributes['password']) && $attributes['password'] !== '') {
			$attributes['passwordRepeat'] = $attributes['password'];
		}
		// -- -- -- --

		$user->attributes = $attributes;
		return (int) $user->save(true, array_keys($attributes));
	}

	public function actionDeleteHistory($id) {
		return (int) History::findOne($id)->delete();
	}

	public function actionHistoryChangeQuantity($historyId, $productId, $quantity) {
		/** @var History $history */
		$history = History::findOne($historyId);
		return (int) $history->setProductQuantity($productId, $quantity);
	}

	public function actionContractorsDelete($id) {
		return (int) Contractor::findOne($id)->delete();
	}

	public function actionCustomersDelete($id) {
		return (int) Customer::findOne($id)->delete();
	}

	public function actionGetCustomers($q = null) {
		$sql    = "SELECT id, name FROM " . Customer::tableName();
		$params = [];
		if ($q !== null) {
			$sql .= " WHERE name LIKE :name";
			$params = [':name' => "%{$q}%"];
		}
		$customers = \Yii::$app->db->createCommand($sql, $params)->queryAll();

		$html = Html::tag('option', '');
		foreach ($customers as $customer) {
			$html .= "\n" . Html::tag('option', $customer['name'], ['value' => $customer['id']]);
		}
		return $html;
	}

	public function actionGetContractors($q = null) {
		$sql    = "SELECT id, companyName FROM " . Contractor::tableName();
		$params = [];
		if ($q !== null) {
			$sql .= " WHERE companyName LIKE :name";
			$params = [':name' => "%{$q}%"];
		}
		$contractors = \Yii::$app->db->createCommand($sql, $params)->queryAll();

		$html = Html::tag('option', '');
		foreach ($contractors as $contractor) {
			$html .= "\n" . Html::tag('option', $contractor['companyName'], ['value' => $contractor['id']]);
		}
		return $html;
	}

	/**
	 * Set form values to the session to view the statistic report
	 *
	 * @param string $type report type
	 * @param string $customer just a label
	 * @param string $contractor just a label
	 * @param string $member value of chosen type and label
	 */
	public function actionStatisticChangeType($type, $customer, $contractor, $member) {
		$statisticProducts = Yii::$app->session->get(self::STATISTIC_PRODUCT_SESSION_KEY, []);
		if (count($statisticProducts) == 0) {
			return;
		}

		$pageTitle = $pageName = '';
		switch ($type) {
			case StatisticsForm::TYPE_CONTRACTOR:
				$pageTitle = '受領書';
				$pageName = $contractor;
				break;
			case StatisticsForm::TYPE_CUSTOMER:
				$pageTitle = '注文書';
				$pageName = $customer;
				break;
		}
		foreach ($statisticProducts as &$statisticProduct) {
			$statisticProduct['pageTitle'] = $pageTitle;
			$statisticProduct['pageName']  = $pageName;
			$statisticProduct['member']    = $member;
			$statisticProduct['type']      = $type;
		}
		unset($statisticProduct);

		$statisticProducts = StatisticsForm::recalculatePrices($statisticProducts);
		Yii::$app->session->set(self::STATISTIC_PRODUCT_REPORT_SESSION_KEY, $statisticProducts);
	}
}

protected/controllers/MainController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\Contractor;
use app\models\Customer;
use app\models\History;
use app\models\Product;
use app\models\StatisticsForm;
use app\models\User;
use Yii;
use yii\base\Exception;
use yii\filters\AccessControl;
use app\models\LoginForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\StringHelper;
use yii\helpers\Url;
use yii\data\Pagination;
use yii\image\drivers\Image;
use yii\image\drivers\Image_GD;
use yii\web\Cookie;
use yii\web\HttpException;

class MainController extends BaseController {

	protected $_perPage;

	public function init() {
		$this->_perPage = Yii::$app->params['perPage'];
	}

	public function actions() {
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
//			'captcha' => [
//				'class'           => 'yii\captcha\CaptchaAction',
//				'fixedVerifyCode' => YII_ENV_TEST? 'testme': null,
//			],
		];
	}

	public function actionIndex() {
		return $this->redirect(['catalog']);
	}

	public function actionCatalog() {
		$categories        = Category::find()->all();
		$this->view->title = '注文選択';
		return $this->render('catalog', [
			'categories' => $categories,
		]);
	}

	public function actionMail() {
		$this->view->title = '注文送信';
		if (Yii::$app->request->isPost && Yii::$app->request->post('clear') !== null) {
			Product::clearCart(Yii::$app->request->post('clear'));
		}

		$cart          = Product::getCart();
		$productGroups = Product::getGroupedByCompanyProducts($cart);

		$history         = new History();
		$history->cart   = $cart;
		$history->sent   = 1;
		$history->userId = Yii::$app->user->id;

		if (!count($cart)) {
			return $this->redirect(['catalog']);
		}

		if (Yii::$app->request->isPost) { // simple post is when user choose a customer
			// -- Save order cart
			$history->load(Yii::$app->request->post());
			// -- -- -- --
		}

		if (Yii::$app->request->isPost && Yii::$app->request->post('send') !== null) {
			$history->scenario = History::SCENARIO_SEND;

			if ($history->save()) {
				foreach (Yii::$app->request->post('company', []) as $i => $company) {
					$this->_sendHistoryEmail($company, $cart, $productGroups, $history, Yii::$app->request->post('comment')[$i]);
				}
				Product::clearCart();

				return $this->redirect(['main/history-edit', 'id' => $history->id, 'afterSent' => 1]);
			}
		}

		$params = Product::getJSONCart($cart, $productGroups, $history->getNumber(), @$history->customer->name, Yii::$app->user->getIdentity()->username);

		return $this->render('mail', [
			'cart'          => $cart,
			'productGroups' => $productGroups,
			'params'        => $params,
			'companies'     => Contractor::find()->indexBy('id')->all(),
			'history'       => $history,
		]);
	}

	public function actionLogin() {
		if (!\Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new LoginForm();
		$users = User::find()->all();
		if ($model->load(Yii::$app->request->post()) && $model->login()) {
			return $this->goBack();
		} else {
			return $this->render('login', [
				'model' => $model,
				'users' => $users,
			]);
		}
	}

	public function actionLogout() {
		Yii::$app->user->logout();

		return $this->goHome();
	}

	private function _processHistoryPost() {
		if (Yii::$app->request->isPost) {
			$data = Yii::$app->request->post(StringHelper::basename(History::className()));

			if (array_key_exists('given', $data)) {
				/** @var History $history */
				$history        = History::findOne($data['given']);
				$history->given = 1;
				$history->save();
			}
		}
	}

	private function _actionHistory($histories, $perPage, $totalCount) {
		$pages = new Pagination(['totalCount' => $totalCount]);
		$pages->setPageSize($perPage);

		return $this->render('history', [
			'histories' => $histories,
			'pages'     => $pages,
		]);
	}

	public function actionMasterHistory($page = 1, $perPage = null, $sortDirection = 'desc') {
		if ($perPage === null) {
			$perPage = $this->_perPage;
		}
		$this->view->title = '履歴一覧';

		$this->_processHistoryPost();

		$searchQuery = Yii::$app->request->get('q');

		/** @var History[] $histories */
		$histories = History::find()
			->with('user')
			->searchByRelative(User::tableName(), 'creatorUserId', 'id', 'username', $searchQuery)
			->orderBy('created ' . strtoupper($sortDirection))
			->offset($perPage * ($page - 1))
			->limit($perPage)
			->all();

		$totalCount = History::find()
			->searchByRelative(User::tableName(), 'creatorUserId', 'id', 'username', $searchQuery)
			->count();

		return $this->_actionHistory($histories, $perPage, $totalCount);
	}

	public function actionHistory($page = 1, $perPage = null, $sortDirection = 'desc') {
		return $this->actionMasterHistory($page, $perPage, $sortDirection);
	}

	public function actionMaster() {
		$this->view->title = 'マスタ一覧';
		return $this->render('master');
	}

	public function actionSettings() {
		$this->view->title = '設定';
		return $this->render('settings');
	}

	public function actionUsers() {
		$this->view->title = 'スタッフマスター';

		$searchQuery = Yii::$app->request->get('q');
		$users       = User::find()
			->searchBy('username', $searchQuery)
			->all();

		return $this->render('users', [
			'users' => $users,
		]);
	}

	public function actionUsersAdd() {
		$user = new User();

		if (Yii::$app->request->isPost) {
			$user->attributes = Yii::$app->request->post(StringHelper::basename($user::className()));

			if ($user->save()) {
				return $this->redirect(['users']);
			}
		}

		return $this->render('users-add', [
			'user' => $user,
		]);
	}

	public function actionProducts($page = 1, $perPage = null) {
		if ($perPage === null) {
			$perPage = $this->_perPage;
		}
		$this->view->title = '商品一覧';

		$searchQuery = Yii::$app->request->get('q');
		$products    = Product::find()
			->with('category')
			->searchBy('title', $searchQuery)
			->offset($perPage * ($page - 1))
			->limit($perPage)
			->all();

		$pages = new Pagination(['totalCount' => Product::find()->searchBy('title', $searchQuery)->count()]);
		$pages->setPageSize($perPage);
		$this->_saveCurrentPage();
		return $this->render('products', [
			'products' => $products,
			'pages'    => $pages,
		]);
	}

	protected function _saveProductImage(Product $product) {
		$files = $_FILES[StringHelper::basename($product::className())];

		if (count($files['name']) == 0 || !$files['name']['picture']) {
			return;
		}

		/** @var Image_GD $image */
		$image = Yii::$app->image->load($files['tmp_name']['picture']);
		$image->resize(Yii::$app->params['productImageWidth'], Yii::$app->params['productImageHeight']);

		$ext = null;
		switch ($image->type) {
			case IMAGETYPE_JPEG:
			case IMAGETYPE_JPEG2000:
				$ext = 'jpg';
				break;
			case IMAGETYPE_GIF:
				$ext = 'gif';
				break;
			case IMAGETYPE_BMP:
				$ext = 'bmp';
				break;
			case IMAGETYPE_PNG:
				$ext = 'png';
				break;
		}
		$filename = $ext? md5_file($files['tmp_name']['picture']) . '.' . $ext: $files['name']['picture'];
		if ($image->save(Yii::getAlias('@webroot') . $product->getImagePath() . DIRECTORY_SEPARATOR . $filename)) {
			$product->picture = $filename;
		}
	}

	public function actionProductsEdit($id) {
		$this->view->title = '商品変更';
		/** @var Product $product */
		$product = Product::findOne($id);

		if (Yii::$app->request->isPost) {
			$product->attributes = Yii::$app->request->post(StringHelper::basename(get_class($product)));

			$this->_saveProductImage($product);

			if ($product->save()) {
				return $this->redirect(['products']);
			}
		}

		return $this->render('products-edit', [
			'product'     => $product,
			'categories'  => Category::find()->all(),
			'contractors' => Contractor::find()->all(),
			'currentPage' => $this->_getCurrentPage(),
		]);
	}

	public function actionProductsAdd() {
		$this->view->title = '商品追加';
		$product           = new Product();

		if (Yii::$app->request->isPost) {
			$requestIndex        = StringHelper::basename($product::className());
			$product->attributes = Yii::$app->request->post($requestIndex);

			$this->_saveProductImage($product);

			if ($product->save()) {
				return $this->redirect(['products']);
			}
		}

		return $this->render('products-edit', [
			'addMode'     => true,
			'product'     => $product,
			'categories'  => Category::find()->all(),
			'contractors' => Contractor::find()->all(),
		]);
	}

	public function actionHistoryShow($id) {
		/** @var History $history */
		$history       = History::findOne($id);
		$cart          = $history->cart;
		$productGroups = Product::getGroupedByCompanyProducts($cart);
		$params        = Product::getJSONCart($cart, $productGroups);

		return $this->render('history-show', [
			'cart'          => $cart,
			'productGroups' => $productGroups,
			'params'        => $params,
		]);
	}

	/**
	 *
	 *
	 * @author Lukin A.
	 *
	 * @param int     $company ID of company
	 * @param array   $cart
	 * @param array   $productGroups
	 * @param History $history model of history for sending date and number in PDF
	 * @param string  $comment
	 * @return bool
	 * @throws HttpException
	 */
	protected function _sendHistoryEmail($company, $cart, $productGroups, $history, $comment = '') {
		$contractor = Contractor::findOne($company); /** @var $contractor Contractor */
		$pdf = new \mPDF('','A4',0,'sun-exta');
		$pdf->WriteHTML(
			$this->render('@views/mail/mail', [
				'comment'    => $comment,
				'cart'       => $cart,
				'products'   => $productGroups[$company],
				'contractor' => $contractor,
				'history'    => $history,
			])
		);

		/** @var Contractor $contractor */
		$contractor = Contractor::findOne($company);
		if (!$contractor) {
			throw new HttpException(404, "Contractor with id = {$company} not found");
		}

		/** @var \app\models\User $user */
		$user = Yii::$app->user->getIdentity();
		$sent = Yii::$app->mailer
			->compose()
			->setTextBody($comment)
			->attachContent($pdf->Output('', 'S'), ['fileName' => 'attachment.pdf', 'contentType' => 'application/pdf'])

protected/views/main/catalog.php
<?php

use yii\helpers\Html;
use \yii\helpers\Url;

/**
 * @var $this       yii\web\View
 * @var $categories \app\models\Category[]
 **/

$this->registerJsFile('/js/cart.js', ['depends' => ['yii\web\JqueryAsset']]);
?>

<ul class="nav nav-tabs green-tabs">
	<?php foreach ($categories as $i => $category) {
		echo Html::tag('li', Html::a($category->title, "#category{$i}", ['data-toggle' => 'tab']), $i == 0? ['class' => 'active']: []);
	} ?>
</ul>

<div class="tab-content green-tabs__content js-products">
	<?php foreach ($categories as $i => $category) { ?>
		<div class="tab-pane fade<?= $i == 0? ' active in': '' ?>" id="<?= "category{$i}" ?>">
			<div class="row">
				<?php foreach ($category->products as $product) { ?>
					<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
						<div class="product js-product<?= $product->checkIsInCart()? ' product_checked': '' ?>"
							 data-product-id="<?= $product->id ?>"
							 data-add-to-cart-url="<?= Url::to(['ajax/add-to-cart']) ?>"
							 data-remove-from-cart-url="<?= Url::to(['ajax/remove-from-cart']) ?>"
							>
							<?= Html::img($product->imageUrl) ?>
							<div class="product__info">
								<div><?= $product->title ?></div>
								<div class="product__company"><?= @$product->company->companyName ?></div>
								<div class="product__price">
									¥<?= Yii::$app->formatter->asDecimal($product->price, 0) ?>
								</div>
							</div>
						</div>
					</div>
				<?php } ?>
			</div>
		</div>
	<?php } ?>
</div>

protected/views/main/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

	<h1><?= Html::encode($this->title) ?></h1>

	<div class="alert alert-danger">
		<?= nl2br(Html::encode($message)) ?>
	</div>

	<p>
		The above error occurred while the Web server was processing your request.
	</p>

	<p>
		Please contact us if you think this is a server error. Thank you.
	</p>

</div>

protected/views/main/history-edit.php
<?php

use \yii\helpers\Html;
use \yii\helpers\Url;
use \yii\helpers\ArrayHelper;
use yii\bootstrap\ActiveForm;
use app\components\CustomerSelectWidget;

/**
 * @var  yii\web\View          $this
 * @var  \app\models\Product[] $products
 * @var array                  $cart
 * @var array                  $productGroups
 * @var string                 $params
 * @var \app\models\History    $history
 * @var bool                   $sendNew
 * @var bool                   $afterSent
 **/

$this->registerJsFile('js/history.js', ['depends' => ['yii\web\JqueryAsset']]);

/** @var \app\models\User $user */
$user = Yii::$app->user->getIdentity();

$companies = ArrayHelper::map($companies, 'id', 'email');
?>

<?php $form = ActiveForm::begin(['options' => ['method' => 'post']]); ?>

	<?php if (!$afterSent) { ?>
		<h4>No. <?= $history->getNumber() ?></h4>

		<?php foreach ($productGroups as $company => $products) { ?>
			<input type="hidden" name="company[]" value="<?= $company ?>">

			<div class="shadowed-box padded-box">
				<p>送信者： <?= $user->senderEmail ?></p>

				<p>受信者： <?= @$companies[$company] ?></p>

				<p>注文：</p>

				<?= $this->render('@parts/product-table', [
					'products' => $products,
					'cart'     => $cart,
					'editMode' => true,
				]) ?>

				<div class="row">
					<div class="col-xs-4">
						<button type="submit" class="btn btn-primary button-blue button-blue_grey"
								name="delete"><span class="glyphicon glyphicon-remove"></span>破棄
						</button>
					</div>
					<div class="col-xs-8">
						<div class="pull-right">
							<?php if (!$sendNew) { ?>
								<button type="submit" class="btn btn-primary button-blue button-blue_grey"
										name="save"><span class="glyphicon glyphicon-save-file"></span>保存
								</button>
							<?php } ?>
						</div>
					</div>
				</div>
			</div>
		<?php } ?>
	<?php } ?>

	<div class="padded-box padded-box_no-margin-bottom light-grey-bg clearfix">
		<?php if ($afterSent) { ?>
			<h1>送信しました</h1>
		<?php } ?>

		<?= CustomerSelectWidget::widget([
			'form'                 => $form,
			'history'              => $history,
			'options'              => [
				'class'       => 'js-disable-on-change form-control',
				'data-target' => '[name=send]',
			],
		]) ?>

		<button type="submit" class="btn btn-primary button-blue pull-right js-disable-on-change" name="send" data-target="[name=send]"
			<?= $afterSent || !$history->customerId? 'disabled': ''?>><span
			class="glyphicon glyphicon-envelope"></span>送信</button>
		<a href='<?= Url::to(['ajax/get-json']) . '?params=' . $params ?>'
		   target="_blank"
		   class="btn btn-primary button-blue pull-right"><span class="glyphicon glyphicon-print"></span>プリントアウト</a>
		<a class="btn btn-primary button-blue button-blue_grey" href="<?= Url::to(['main/history']) ?>"><span
				class="icon-back"></span>戻る
		</a>
	</div>

<?php ActiveForm::end(); ?>

protected/views/main/history-show.php
<?php

use yii\helpers\Html;
use \yii\helpers\Url;
use \app\models\Product;

/**
 * @var  yii\web\View          $this
 * @var  \app\models\Product[] $products
 * @var array                  $cart
 * @var array                  $productGroups
 * @var string                 $params
 **/
?>

<?php foreach ($productGroups as $company => $products) { ?>
	<div class="shadowed-box padded-box">
		<p>注文：</p>

		<?= $this->render('@parts/product-table', [
			'products' => $products,
			'cart'     => $cart,
		]) ?>
	</div>
<?php } ?>

<div class="clearfix">
	<a href='<?= Url::to(['ajax/get-json']) . '?params=' . $params ?>' target="_blank"
	   class="btn btn-primary button-blue pull-right"><span class="glyphicon glyphicon-print"></span>プリントアウト</a>
</div>

protected/views/main/products.php
<?php

use yii\helpers\Html;
use \yii\helpers\Url;
use yii\widgets\LinkPager;

/**
 * @var  yii\web\View          $this
 * @var  \app\models\Product[] $products
 * @var \yii\data\Pagination   $pages
 **/
?>

	<div class="shadowed-box">
		<table class="table table-hover table-grey table-grey_no-border table-edit js-edit-table">
			<colgroup>
				<col width="5%">
				<col width="10%">
				<col width="10%">
				<col width="10%">
				<col width="10%">
				<col width="10%">
				<col width="10%">
				<col width="25%">
			</colgroup>
			<tr>
				<th>No.</th>
				<th>画像</th>
				<th>商品名</th>
				<th>値段 <span style="font-weight: normal">(税込み)</span></th>
				<th>仕入れ値</th>
				<th>供給者</th>
				<th>カテゴリー</th>
				<th>商品コード</th>
				<th></th>
			</tr>
			<?php foreach ($products as $product) { ?>
				<tr>
					<td><?= $product->id ?></td>
					<td>
						<?php if ($product->picture) {
							echo Html::img($product->getImageUrl());
						} ?>
					</td>
					<td><?= $product->title ?></td>
					<td><?= $product->price ?>円</td>
					<td><?= $product->purchasePrice?: 0 ?>円</td>
					<td><?= @$product->company->companyName ?></td>
					<td><?= $product->category->title ?></td>
					<td><?= $product->code ?></td>
					<td>
						<div class="table-edit__controls">
							<a href="<?= Url::to(['main/products-edit', 'id' => $product->id]) ?>"
							   class="table-edit__control table-edit__control_edit"><span
									class="table-edit__controls-label">編集</span></a>
							<button class="table-edit__control table-edit__control_delete" data-delete
									data-delete-url="<?= Url::to(['ajax/delete-product', 'id' => $product->id]) ?>">
								<span class="table-edit__controls-label">削除</span></button>
						</div>
					</td>
				</tr>
			<?php } ?>
		</table>

		<div class="padded-box">
			<?= LinkPager::widget([
				'pagination' => $pages,
			]); ?>
		</div>

		<div class="padded-box padded-box_no-margin-bottom light-grey-bg clearfix">
			<a href="<?= Url::to(['main/products-add']) ?>" class="pull-right btn btn-primary button-blue" name="send"><span class="glyphicon glyphicon-plus"></span>登録</a>
		</div>
	</div>

<?= $this->render('@parts/modal', [
	'text' => '注文を削除します。<br>よろしいですか？',
]) ?>

protected/views/main/users.php
<?php

use yii\helpers\Html;
use \yii\helpers\Url;
use \app\models\User;

/**
 * @var  yii\web\View       $this
 * @var  \app\models\User[] $users
 **/
?>

<div class="shadowed-box">
	<table class="table table-hover table-grey table-grey_no-border table-edit js-edit-table">
		<colgroup>
			<col width="5%">
			<col width="25%">
			<col width="20%">
			<col width="20%">
			<col width="30%">
		</colgroup>
		<tr>
			<th>No.</th>
			<th>担当者</th>
			<th>パスワード</th>
			<th>権限</th>
			<th></th>
		</tr>

		<?php foreach ($users as $user) { ?>
			<tr data-read-row>
				<td><?= $user->id ?></td>
				<td><?= $user->username ?></td>
				<td>********</td>
				<td><?= $user->role ?></td>
				<td>
					<div class="table-edit__controls">
						<button class="table-edit__control table-edit__control_edit" data-edit><span class="table-edit__controls-label">編集</span></button>
						<?php if (count($users) > 1) { ?>
							<button class="table-edit__control table-edit__control_delete" data-delete data-delete-url="<?= Url::to(['ajax/delete-user', 'id' => $user->id]) ?>"><span class="table-edit__controls-label">削除</span></button>
						<?php } ?>
					</div>
				</td>
			</tr>
			<tr class="hidden" data-edit-row data-serialize-elements data-url="<?= Url::to(['ajax/change-user']) ?>">
				<td><?= $user->id ?></td>
				<td>
					<input type="hidden" name="id" value="<?= $user->id ?>">
					<input class="form-control" type="text" name="username" value="<?= $user->username ?>">
				</td>
				<td><input class="form-control" type="password" name="password" value=""></td>
				<td>
					<select class="form-control" name="role">
						<?php foreach (User::getRoles() as $roleLabel) {
							echo Html::tag('option', $roleLabel);
						} ?>
					</select>
				</td>
				<td>
					<div class="table-edit__controls">
						<button class="table-edit__control" data-accept><span class="table-edit__controls-label">保存</span></button>
						<button class="table-edit__control table-edit__control_cancel" data-cancel><span class="table-edit__controls-label">取消</span></button>
					</div>
				</td>
			</tr>
		<?php } ?>
	</table>

	<div class="padded-box padded-box_no-margin-bottom light-grey-bg clearfix">
		<a class="btn btn-primary button-blue button-blue_grey" href="<?= Url::to(['main/master']) ?>"><span
				class="icon-back"></span>戻る
		</a>
		<a href="<?= Url::to(['main/users-add']) ?>" class="pull-right btn btn-primary button-blue" name="send"><span class="glyphicon glyphicon-plus"></span>登録</a>
	</div>
</div>

<?= $this->render('@parts/modal', [
	'text' => '削除してもよろしですか？',
]) ?>