protected/controllers/AjaxController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\Contractor;
use app\models\Customer;
use app\models\History;
use app\models\Product;
use app\models\StatisticsForm;
use app\models\User;
use Yii;
use yii\bootstrap\Html;
use yii\helpers\ArrayHelper;

class AjaxController extends BaseController {

	public $layout = false;

	public function actionAddToCart($productId) {
		Product::addToCart($productId);
	}

	public function actionRemoveFromCart() {
		$productIds = Yii::$app->request->get('productId');
		if ($productIds) {
			Product::removeFromCart($productIds);
		}
	}

	public function actionGetCart() {
		$cart = Product::getCart();

		$productsInCartOrdered = [];
		if (count($cart)) {
			$productIds = array_keys($cart);
			$productsInCart = Product::find()->where(['id' => $productIds])->indexBy('id')->all();
			foreach ($productIds as $productId) {
				$productsInCartOrdered[$productId] = $productsInCart[$productId];
			}
			unset($productsInCart); // save memory)))
		}

		return $this->render('@parts/cart', [
			'products' => $productsInCartOrdered,
			'cart'     => $cart,
			'sum'      => Product::getCartSum(),
		]);
	}

	public function actionChangeQuantity($productId, $quantity) {
		$cart             = Product::getCart();
		$cart[$productId] = $quantity;
		Product::setCart($cart);
	}

	public function actionSaveHistory() {
		$history         = new History();
		$history->cart   = serialize(Product::getCart());
		if ($history->save()) {
			// -- Demo saving to the PDF (maybe not demo =)))
			/*$cart     = Product::getCart();
			$products = Product::findAll(array_keys($cart));

			$pdf = new \mPDF();
			$pdf->WriteHTML(
				$this->render('@views/mail/mail', [
					'comment'  => '',
					'cart'     => $cart,
					'products' => $products,
				])
			);
			$pdfPath = implode(DIRECTORY_SEPARATOR, [
				Yii::getAlias('@webroot'),
				'pdf',
			]);
			if (!file_exists($pdfPath)) {
				@mkdir($pdfPath);
			}
			$pdfName = "cart_{$history->id}.pdf";
			@file_put_contents(implode(DIRECTORY_SEPARATOR, [
				$pdfPath,
				$pdfName,
			]), $pdf->Output('', 'S'));*/
			// -- -- -- --

			Product::clearCart();
			return $this->redirect(['main/history']);
		}
		return $this->redirect(['main/catalog']);
	}

	public function actionGetCounter() {
		return $this->render('@parts/cart-counter');
	}

	public function actionGetJson() {
		$params = Yii::$app->request->get('params');
		return $this->renderJson(json_decode($params, true));
	}

	public function actionDeleteProduct($id) {
		return (int) Product::findOne($id)->delete();
	}

	public function actionDeleteUser($id) {
		if (User::find()->count() < 2) {
			return 0;
		}
		return (int) User::findOne($id)->delete();
	}

	public function actionChangeUser() {
		$attributes = Yii::$app->request->post(null, []);
		if (count($attributes) == 0) {
			Yii::$app->end();
		}

		/** @var User $user */
		$user = User::findOne($attributes['id']);
		$user->save(true, array_keys($attributes));

		// -- We can not switch off rules for password only, so copy password if exists
		if (isset($attributes['password']) && $attributes['password'] !== '') {
			$attributes['passwordRepeat'] = $attributes['password'];
		}
		// -- -- -- --

		$user->attributes = $attributes;
		return (int) $user->save(true, array_keys($attributes));
	}

	public function actionDeleteHistory($id) {
		return (int) History::findOne($id)->delete();
	}

	public function actionHistoryChangeQuantity($historyId, $productId, $quantity) {
		/** @var History $history */
		$history = History::findOne($historyId);
		return (int) $history->setProductQuantity($productId, $quantity);
	}

	public function actionContractorsDelete($id) {
		return (int) Contractor::findOne($id)->delete();
	}

	public function actionCustomersDelete($id) {
		return (int) Customer::findOne($id)->delete();
	}

	public function actionGetCustomers($q = null) {
		$sql    = "SELECT id, name FROM " . Customer::tableName();
		$params = [];
		if ($q !== null) {
			$sql .= " WHERE name LIKE :name";
			$params = [':name' => "%{$q}%"];
		}
		$customers = \Yii::$app->db->createCommand($sql, $params)->queryAll();

		$html = Html::tag('option', '');
		foreach ($customers as $customer) {
			$html .= "\n" . Html::tag('option', $customer['name'], ['value' => $customer['id']]);
		}
		return $html;
	}

	public function actionGetContractors($q = null) {
		$sql    = "SELECT id, companyName FROM " . Contractor::tableName();
		$params = [];
		if ($q !== null) {
			$sql .= " WHERE companyName LIKE :name";
			$params = [':name' => "%{$q}%"];
		}
		$contractors = \Yii::$app->db->createCommand($sql, $params)->queryAll();

		$html = Html::tag('option', '');
		foreach ($contractors as $contractor) {
			$html .= "\n" . Html::tag('option', $contractor['companyName'], ['value' => $contractor['id']]);
		}
		return $html;
	}

	/**
	 * Set form values to the session to view the statistic report
	 *
	 * @param string $type report type
	 * @param string $customer just a label
	 * @param string $contractor just a label
	 * @param string $member value of chosen type and label
	 */
	public function actionStatisticChangeType($type, $customer, $contractor, $member) {
		$statisticProducts = Yii::$app->session->get(self::STATISTIC_PRODUCT_SESSION_KEY, []);
		if (count($statisticProducts) == 0) {
			return;
		}

		$pageTitle = $pageName = '';
		switch ($type) {
			case StatisticsForm::TYPE_CONTRACTOR:
				$pageTitle = '受領書';
				$pageName = $contractor;
				break;
			case StatisticsForm::TYPE_CUSTOMER:
				$pageTitle = '注文書';
				$pageName = $customer;
				break;
		}
		foreach ($statisticProducts as &$statisticProduct) {
			$statisticProduct['pageTitle'] = $pageTitle;
			$statisticProduct['pageName']  = $pageName;
			$statisticProduct['member']    = $member;
			$statisticProduct['type']      = $type;
		}
		unset($statisticProduct);

		$statisticProducts = StatisticsForm::recalculatePrices($statisticProducts);
		Yii::$app->session->set(self::STATISTIC_PRODUCT_REPORT_SESSION_KEY, $statisticProducts);
	}
}

protected/controllers/MainController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\Contractor;
use app\models\Customer;
use app\models\History;
use app\models\Product;
use app\models\StatisticsForm;
use app\models\User;
use Yii;
use yii\base\Exception;
use yii\filters\AccessControl;
use app\models\LoginForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\StringHelper;
use yii\helpers\Url;
use yii\data\Pagination;
use yii\image\drivers\Image;
use yii\image\drivers\Image_GD;
use yii\web\Cookie;
use yii\web\HttpException;

class MainController extends BaseController {

	protected $_perPage;

	public function init() {
		$this->_perPage = Yii::$app->params['perPage'];
	}

	public function actions() {
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
//			'captcha' => [
//				'class'           => 'yii\captcha\CaptchaAction',
//				'fixedVerifyCode' => YII_ENV_TEST? 'testme': null,
//			],
		];
	}

	public function actionIndex() {
		return $this->redirect(['catalog']);
	}

	public function actionCatalog() {
		$categories        = Category::find()->all();
		$this->view->title = '注文選択';
		return $this->render('catalog', [
			'categories' => $categories,
		]);
	}

	public function actionMail() {
		$this->view->title = '注文送信';
		if (Yii::$app->request->isPost && Yii::$app->request->post('clear') !== null) {
			Product::clearCart(Yii::$app->request->post('clear'));
		}

		$cart          = Product::getCart();
		$productGroups = Product::getGroupedByCompanyProducts($cart);

		$history         = new History();
		$history->cart   = $cart;
		$history->sent   = 1;
		$history->userId = Yii::$app->user->id;

		if (!count($cart)) {
			return $this->redirect(['catalog']);
		}

		if (Yii::$app->request->isPost) { // simple post is when user choose a customer
			// -- Save order cart
			$history->load(Yii::$app->request->post());
			// -- -- -- --
		}

		if (Yii::$app->request->isPost && Yii::$app->request->post('send') !== null) {
			$history->scenario = History::SCENARIO_SEND;

			if ($history->save()) {
				foreach (Yii::$app->request->post('company', []) as $i => $company) {
					$this->_sendHistoryEmail($company, $cart, $productGroups, $history, Yii::$app->request->post('comment')[$i]);
				}
				Product::clearCart();

				return $this->redirect(['main/history-edit', 'id' => $history->id, 'afterSent' => 1]);
			}
		}

		$params = Product::getJSONCart($cart, $productGroups, $history->getNumber(), @$history->customer->name, Yii::$app->user->getIdentity()->username);

		return $this->render('mail', [
			'cart'          => $cart,
			'productGroups' => $productGroups,
			'params'        => $params,
			'companies'     => Contractor::find()->indexBy('id')->all(),
			'history'       => $history,
		]);
	}

	public function actionLogin() {
		if (!\Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new LoginForm();
		$users = User::find()->all();
		if ($model->load(Yii::$app->request->post()) && $model->login()) {
			return $this->goBack();
		} else {
			return $this->render('login', [
				'model' => $model,
				'users' => $users,
			]);
		}
	}

	public function actionLogout() {
		Yii::$app->user->logout();

		return $this->goHome();
	}

	private function _processHistoryPost() {
		if (Yii::$app->request->isPost) {
			$data = Yii::$app->request->post(StringHelper::basename(History::className()));

			if (array_key_exists('given', $data)) {
				/** @var History $history */
				$history        = History::findOne($data['given']);
				$history->given = 1;
				$history->save();
			}
		}
	}

	private function _actionHistory($histories, $perPage, $totalCount) {
		$pages = new Pagination(['totalCount' => $totalCount]);
		$pages->setPageSize($perPage);

		return $this->render('history', [
			'histories' => $histories,
			'pages'     => $pages,
		]);
	}

	public function actionMasterHistory($page = 1, $perPage = null, $sortDirection = 'desc') {
		if ($perPage === null) {
			$perPage = $this->_perPage;
		}
		$this->view->title = '履歴一覧';

		$this->_processHistoryPost();

		$searchQuery = Yii::$app->request->get('q');

		/** @var History[] $histories */
		$histories = History::find()
			->with('user')
			->searchByRelative(User::tableName(), 'creatorUserId', 'id', 'username', $searchQuery)
			->orderBy('created ' . strtoupper($sortDirection))
			->offset($perPage * ($page - 1))
			->limit($perPage)
			->all();

		$totalCount = History::find()
			->searchByRelative(User::tableName(), 'creatorUserId', 'id', 'username', $searchQuery)
			->count();

		return $this->_actionHistory($histories, $perPage, $totalCount);
	}

	public function actionHistory($page = 1, $perPage = null, $sortDirection = 'desc') {
		return $this->actionMasterHistory($page, $perPage, $sortDirection);
	}

	public function actionMaster() {
		$this->view->title = 'マスタ一覧';
		return $this->render('master');
	}

	public function actionSettings() {
		$this->view->title = '設定';
		return $this->render('settings');
	}

	public function actionUsers() {
		$this->view->title = 'スタッフマスター';

		$searchQuery = Yii::$app->request->get('q');
		$users       = User::find()
			->searchBy('username', $searchQuery)
			->all();

		return $this->render('users', [
			'users' => $users,
		]);
	}

	public function actionUsersAdd() {
		$user = new User();

		if (Yii::$app->request->isPost) {
			$user->attributes = Yii::$app->request->post(StringHelper::basename($user::className()));

			if ($user->save()) {
				return $this->redirect(['users']);
			}
		}

		return $this->render('users-add', [
			'user' => $user,
		]);
	}

	public function actionProducts($page = 1, $perPage = null) {
		if ($perPage === null) {
			$perPage = $this->_perPage;
		}
		$this->view->title = '商品一覧';

		$searchQuery = Yii::$app->request->get('q');
		$products    = Product::find()
			->with('category')
			->searchBy('title', $searchQuery)
			->offset($perPage * ($page - 1))
			->limit($perPage)
			->all();

		$pages = new Pagination(['totalCount' => Product::find()->searchBy('title', $searchQuery)->count()]);
		$pages->setPageSize($perPage);
		$this->_saveCurrentPage();
		return $this->render('products', [
			'products' => $products,
			'pages'    => $pages,
		]);
	}

	protected function _saveProductImage(Product $product) {
		$files = $_FILES[StringHelper::basename($product::className())];

		if (count($files['name']) == 0 || !$files['name']['picture']) {
			return;
		}

		/** @var Image_GD $image */
		$image = Yii::$app->image->load($files['tmp_name']['picture']);
		$image->resize(Yii::$app->params['productImageWidth'], Yii::$app->params['productImageHeight']);

		$ext = null;
		switch ($image->type) {
			case IMAGETYPE_JPEG:
			case IMAGETYPE_JPEG2000:
				$ext = 'jpg';
				break;
			case IMAGETYPE_GIF:
				$ext = 'gif';
				break;
			case IMAGETYPE_BMP:
				$ext = 'bmp';
				break;
			case IMAGETYPE_PNG:
				$ext = 'png';
				break;
		}
		$filename = $ext? md5_file($files['tmp_name']['picture']) . '.' . $ext: $files['name']['picture'];
		if ($image->save(Yii::getAlias('@webroot') . $product->getImagePath() . DIRECTORY_SEPARATOR . $filename)) {
			$product->picture = $filename;
		}
	}

	public function actionProductsEdit($id) {
		$this->view->title = '商品変更';
		/** @var Product $product */
		$product = Product::findOne($id);

		if (Yii::$app->request->isPost) {
			$product->attributes = Yii::$app->request->post(StringHelper::basename(get_class($product)));

			$this->_saveProductImage($product);

			if ($product->save()) {
				return $this->redirect(['products']);
			}
		}

		return $this->render('products-edit', [
			'product'     => $product,
			'categories'  => Category::find()->all(),
			'contractors' => Contractor::find()->all(),
			'currentPage' => $this->_getCurrentPage(),
		]);
	}

	public function actionProductsAdd() {
		$this->view->title = '商品追加';
		$product           = new Product();

		if (Yii::$app->request->isPost) {
			$requestIndex        = StringHelper::basename($product::className());
			$product->attributes = Yii::$app->request->post($requestIndex);

			$this->_saveProductImage($product);

			if ($product->save()) {
				return $this->redirect(['products']);
			}
		}

		return $this->render('products-edit', [
			'addMode'     => true,
			'product'     => $product,
			'categories'  => Category::find()->all(),
			'contractors' => Contractor::find()->all(),
		]);
	}

	public function actionHistoryShow($id) {
		/** @var History $history */
		$history       = History::findOne($id);
		$cart          = $history->cart;
		$productGroups = Product::getGroupedByCompanyProducts($cart);
		$params        = Product::getJSONCart($cart, $productGroups);

		return $this->render('history-show', [
			'cart'          => $cart,
			'productGroups' => $productGroups,
			'params'        => $params,
		]);
	}

	/**
	 *
	 *
	 * @author Lukin A.
	 *
	 * @param int     $company ID of company
	 * @param array   $cart
	 * @param array   $productGroups
	 * @param History $history model of history for sending date and number in PDF
	 * @param string  $comment
	 * @return bool
	 * @throws HttpException
	 */
	protected function _sendHistoryEmail($company, $cart, $productGroups, $history, $comment = '') {
		$contractor = Contractor::findOne($company); /** @var $contractor Contractor */
		$pdf = new \mPDF('','A4',0,'sun-exta');
		$pdf->WriteHTML(
			$this->render('@views/mail/mail', [
				'comment'    => $comment,
				'cart'       => $cart,
				'products'   => $productGroups[$company],
				'contractor' => $contractor,
				'history'    => $history,
			])
		);

		/** @var Contractor $contractor */
		$contractor = Contractor::findOne($company);
		if (!$contractor) {
			throw new HttpException(404, "Contractor with id = {$company} not found");
		}

		/** @var \app\models\User $user */
		$user = Yii::$app->user->getIdentity();
		$sent = Yii::$app->mailer
			->compose()
			->setTextBody($comment)
			->attachContent($pdf->Output('', 'S'), ['fileName' => 'attachment.pdf', 'contentType' => 'application/pdf'])

protected/views/_parts/cart-counter.php
<?php
use app\models\Product;
use yii\helpers\Url;

$cartCount = count(Product::getCart());
?>
<?php if ($cartCount) { ?>
	<div class="cart-cloud">
		<a href="<?= Url::to(['main/mail']) ?>"><span class="cart-cloud__list-icon"><span
					class="cart-cloud__cloud"><?= $cartCount ?></span></span></a>
	</div>
<?php } ?>

protected/views/_parts/cart.php
<?php

use yii\helpers\Html;
use yii\i18n\Formatter;
use yii\helpers\Url;

/**
 * @var \app\models\Product[] $products
 * @var array                 $cart
 * @var int                   $sum
 */
?>
<div class="cart-summary-wrapper js-cart-summary">
	<div class="container">
		<div class="cart-summary__icon js-cart-toggle"><span class="glyphicon glyphicon-shopping-cart"></span></div>
	</div>
	<div class="cart-summary">
		<div class="container">
			<div class="row">
				<div class="col-sm-9">
					<div class="cart-summary__table-wrapper">
						<table class="table cart-summary__table">
							<tr>
								<th></th>
								<th>
									<label>
										<input type="checkbox" class="js-cart-select-all">
										&nbsp;&nbsp;&nbsp;商品名
									</label>
								</th>
								<th>単価</th>
								<th>数量</th>
								<th>計</th>
							</tr>
							<?php $i = 1 ?>
							<?php foreach ($products as $product) { ?>
								<tr data-product-id="<?= $product->id ?>">
									<td><?= $i++ ?>.</td>
									<td>
										<label>
											<input type="checkbox" class="js-cart-select">
											&nbsp;&nbsp;&nbsp;<?= $product->title ?></label>
									</td>
									<td><?= $product->price ?></td>
									<td>
										<input type="number" class="form-control js-change-quantity"
											   value="<?= $cart[$product->id] ?>"
											   data-quantity="<?= $cart[$product->id] ?>"
											   data-url="<?= Url::to(['ajax/change-quantity']) ?>">
									</td>
									<td><?= $cart[$product->id] * $product->price ?></td>
								</tr>
							<?php } ?>
						</table>
					</div>
				</div>
				<div class="col-sm-3">
					<a class="white-border-block t-c cart-summary__link <?= count($cart)? '': 'js-empty-cart' ?>" href="<?= Url::to(['main/mail']) ?>">
						<div>合計：</div>
						<div class="cart-summary__sum">¥<?= Yii::$app->formatter->asDecimal($sum, 0) ?></div>
						<div>注文送信&nbsp;&nbsp;&nbsp;<span
									class="glyphicon glyphicon-arrow-right"></span></div>
					</a>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-9">
					<button class="btn cart-summary__button js-remove-products"
							data-url="<?= Url::to(['ajax/remove-from-cart']) ?>"><span
							class="glyphicon glyphicon-trash"></span>&nbsp;&nbsp;&nbsp;明細削除
					</button>
				</div>
				<div class="col-sm-3">
					<?php /*<button class="js-cart-save-history btn cart-summary__button cart-summary__button_w100"
							data-url="<?= Url::to(['ajax/save-history']) ?>">注文保存&nbsp;&nbsp;&nbsp;<span
							class="glyphicon glyphicon-save-file"></span></button>*/ ?>
					<a class="btn cart-summary__button cart-summary__button_w100 <?= count($cart)? '': 'js-empty-cart' ?>" href="<?= Url::to(['ajax/save-history']) ?>">
						注文保存&nbsp;&nbsp;&nbsp;<span
							class="glyphicon glyphicon-save-file"></span>
					</a>
				</div>
			</div>
		</div>
	</div>
</div>

protected/views/_parts/customer-select.php
<?php

use yii\helpers\ArrayHelper;
use yii\helpers\Url;

/**
 * @var \yii\bootstrap\ActiveForm $form
 * @var \app\models\History       $history
 * @var \app\models\Customer[]    $customers
 * @var bool                      $withoutPageReloading
 * @var array                     $options
 */

$form->fieldConfig['template'] = '<div class="row"><div class="col-sm-3">{label}</div><div class="col-sm-9">{input}{error}</div></div>';
?>

<?php // For future best times))) When guys realize that they have too much customers
/*= $form->field($history, 'customerId')
	->dropDownList($history->customerId? [$history->customerId => $history->customer->name]: [], ['class' => 'js-select-picker js-picker-get-options-by-query js-submit-on-change', 'data-url' => Url::to(['ajax/get-customers']), 'prompt' => 'お客様選択'])*/ ?>
<?= $form->field($history, 'customerId')->dropDownList(ArrayHelper::map($customers, 'id', 'name'), $options + [
	'class'  => ($withoutPageReloading? '': 'js-submit-on-change ') . 'form-control',
	'prompt' => 'お客様選択',
]) ?>

<div class="text-right form-group">
	<a href="<?= Url::to(['main/customers-add']) ?>" class="btn btn-primary button-blue button-blue_grey"><span
			class="glyphicon glyphicon-plus"></span>登録</a>
</div>

protected/views/_parts/modal.php
<?php
/**
 * @var string $text
 * @var string $noText
 * @var string $yesText
 */

$yesText = isset($yesText)? $yesText: 'はい';
$noText = isset($noText)? $noText: 'いいえ';
?>

<div class="modal fade modal-red" id="confirmation-modal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-body">
				<?= $text ?>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-danger pull-right js-modal-yes"><?= $yesText ?></button>
				<button type="button" class="btn btn-success js-modal-no"><?= $noText ?></button>
			</div>
		</div>
	</div>
</div>

protected/views/_parts/product-table-report.php
<?php
/**
 * @var \app\models\Product[] $products
 * @var array                 $cart
 * @var bool                  $editMode
 * @var String                $comment
 */

use \yii\helpers\Url;

$comment = isset($comment)? $comment: null;
?>

<table class="table table-grey">
	<tr>
		<th>商品名</th>
		<th>商品コード</th>
		<th>仕入れ値</th>
		<th>数量</th>
		<th>計</th>
	</tr>

	<?php $sum = 0; ?>
	<?php foreach ($products as $product) { ?>
		<tr data-product-id="<?= $product->id ?>">
			<td><?= $product->title ?></td>
			<td><?= $product->code ?></td>
			<td><?= $product->purchasePrice ?></td>
			<td><?= $cart[$product->id]; ?></td>
			<td><?= ($rowTotalPrice = $product->purchasePrice * $cart[$product->id]) ?></td>
		</tr>
		<?php $sum += $rowTotalPrice ?>
	<?php } ?>
	<tr class="table-grey__footer">
		<td style="text-align: left">
			<?php if ($comment !== null) { ?>
				備考: <?= $comment ?>
			<?php } ?>
		</td>
		<td colspan="2">
			小計 <br>
			消費税（8%）<br>
			合計金額
		</td>
		<td>
			¥<?= Yii::$app->formatter->asDecimal($sum, 0) ?><br>
			¥<?= Yii::$app->formatter->asDecimal($sum * 0.08, 0) ?><br>
			¥<?= Yii::$app->formatter->asDecimal($sum * 1.08, 0) ?><br>
		</td>
	</tr>
</table>

protected/views/_parts/product-table.php
<?php
/**
 * @var \app\models\Product[] $products
 * @var array                 $cart
 * @var bool $editMode
 */

use \yii\helpers\Url;

$editMode = isset($editMode) && $editMode?: false;
?>

<table class="table table-grey">
	<tr>
		<?php if ($editMode) { ?>
			<th>
				<label>
					<input type="checkbox" class="js-cart-select-all">
				</label>
			</th>
		<?php } ?>
		<th></th>
		<th>商品名</th>
		<th>商品コード</th>
		<th>単価</th>
		<th>仕入れ値</th>
		<th>数量</th>
		<th>計</th>
	</tr>

	<?php $sum = 0; ?>
	<?php foreach ($products as $i => $product) { ?>
		<tr data-product-id="<?= $product->id ?>">
			<?php if ($editMode) { ?>
				<td>
					<label>
						<input type="checkbox" class="js-cart-select" name="deleteProducts[]" value="<?= $product->id ?>">
					</label>
				</td>
			<?php } ?>
			<td><?= ++$i ?>.</td>
			<td><?= $product->title ?></td>
			<td class="muted"><?= $product->code ?></td>
			<td><?= $product->price ?></td>
			<td><?= $product->purchasePrice ?></td>
			<td>
				<?php if ($editMode) { ?>
					<input type="text" class="form-control table-checkbox" name="quantityProducts[<?= $product->id ?>]"
						   value="<?= $cart[$product->id] ?>" data-quantity="<?= $cart[$product->id] ?>" data-url="<?= Url::to(['ajax/history-change-quantity']) ?>">
				<?php } else {
					echo $cart[$product->id];
				} ?>
			</td>
			<td><?= ($rowTotalPrice = $product->price * $cart[$product->id]) ?></td>
		</tr>
		<?php $sum += $rowTotalPrice ?>
	<?php } ?>
	<tr class="table-grey__footer">
		<td colspan="<?= $editMode? 8: 7 ?>">
			合計： <strong class="red f18">¥<?= Yii::$app->formatter->asDecimal($sum, 0) ?></strong><br>
			税込み
		</td>
	</tr>
</table>

protected/views/_parts/search-form.php
<form action="" class="search-form">
	<div class="input-group">
		<input class="form-control" type="text" name="q" value="<?= Yii::$app->request->get('q') ?>">
		<div class="input-group-btn">
			<button class="btn btn-default"><span class="glyphicon glyphicon-search"></span> 検索</button>
		</div>
	</div>
</form>

protected/views/_parts/statistic-table-report.php
<?php
/**
 * @var array $statisticProducts
 */
?>

<?php
use \app\models\StatisticsForm;

$totalPrice = 0;
$colSpan    = 12;

if (!count($statisticProducts)) {
	return;
}
?>
<table class="table table-hover table-grey table-grey_no-border table-edit js-edit-table">
	<tr>
		<th>商品名</th>
		<th>数量</th>
		<th><?= current($statisticProducts)['type'] == StatisticsForm::TYPE_CUSTOMER? '単価': '仕入れ値' ?></th>
		<th>金額</th>
	</tr>
	<?php foreach ($statisticProducts as $productItem) { ?>
		<tr data-id="<?= $productItem['id'] ?>">
			<td><?= $productItem['title'] ?></td>
			<td><?= $productItem['quantity'] ?></td>
			<td><?= $productItem['price'] ?></td>
			<td><?= $productItem['sum'] ?></td>
		</tr>
		<?php $totalPrice += $productItem['quantity'] * $productItem['price'] ?>
	<?php } ?>
	<tr>
		<td colspan="<?= $colSpan ?>" class="text-right">
			小計: ¥<?= Yii::$app->formatter->asDecimal($totalPrice, 0) ?><br>
			消費税（8%): ¥<?= Yii::$app->formatter->asDecimal($totalPrice * 0.08, 0) ?><br>
			合計金額: ¥<?= Yii::$app->formatter->asDecimal($totalPrice * 1.08, 0) ?><br>
		</td>
	</tr>
</table>